# Generated by Django 5.2.12 on 2026-05-09 21:01

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentbudget',
            name='fiscal_year',
            field=models.CharField(default=finance.models.get_fiscal_year, max_length=9),
        ),
        migrations.AlterField(
            model_name='expense',
            name='fiscal_year',
            field=models.CharField(default=finance.models.get_fiscal_year, max_length=9),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
    ]
