# Generated by Django 5.2.12 on 2026-05-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('worker', 'Field Worker'), ('technician', 'Technician'), ('surveyor', 'Surveyor'), ('admin', 'Department Admin'), ('finance', 'Finance Officer'), ('super_admin', 'Super Admin')], default='citizen', max_length=20),
        ),
    ]
