# Generated by Django 5.2.12 on 2026-05-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_department_head_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('worker', 'Field Worker'), ('technician', 'Technician'), ('surveyor', 'Surveyor'), ('admin', 'Department Admin'), ('finance', 'Finance Officer'), ('super_admin', 'Super Admin')], db_index=True, default='citizen', max_length=20),
        ),
    ]
