# Generated by Django 5.2.12 on 2026-05-09 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_co_reporters_and_more'),
        ('departments', '0002_alter_department_city_corp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('roads', 'Roads & Infrastructure'), ('water', 'Water & Sewerage'), ('electricity', 'Electricity & Street Lights'), ('sanitation', 'Sanitation & Waste'), ('parks', 'Parks & Recreation'), ('health', 'Public Health'), ('building', 'Building & Construction'), ('transport', 'Transport & Traffic'), ('environment', 'Environment & Drainage'), ('fire', 'Fire & Emergency'), ('it', 'IT & Technology'), ('admin_dept', 'General Administration'), ('other', 'Other')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='city_corp',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='is_anonymous',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='is_duplicate',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('assigned', 'Assigned to Surveyor'), ('surveying', 'Survey in Progress'), ('survey_done', 'Survey Complete'), ('budget_pending', 'Budget Pending'), ('budget_approved', 'Budget Approved'), ('worker_assigned', 'Worker Assigned'), ('in_progress', 'Work in Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'department'], name='complaints__status_54874d_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['city_corp', 'category'], name='complaints__city_co_195795_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['citizen', 'status'], name='complaints__citizen_01f312_idx'),
        ),
    ]
