# Generated by Django 5.2.12 on 2026-05-16 05:40

import random
import string

from django.db import migrations, models


def backfill_aliases(apps, schema_editor):
    """Assign anonymous_alias to any existing anonymous complaints that lack one."""
    Complaint = apps.get_model('complaints', 'Complaint')
    chars = string.ascii_uppercase + string.digits
    used = set(Complaint.objects.filter(anonymous_alias__gt='').values_list('anonymous_alias', flat=True))
    for c in Complaint.objects.filter(is_anonymous=True, anonymous_alias=''):
        for _ in range(200):
            alias = 'Anon #' + ''.join(random.choices(chars, k=4))
            if alias not in used:
                c.anonymous_alias = alias
                used.add(alias)
                break
        else:
            alias = 'Anon #' + ''.join(random.choices(chars, k=6))
            c.anonymous_alias = alias
            used.add(alias)
        c.save(update_fields=['anonymous_alias'])


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_add_indexes_and_str_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='anonymous_alias',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.RunPython(backfill_aliases, migrations.RunPython.noop),
    ]
