# Generated by Django 6.0.4 on 2026-05-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(choices=[('roads', 'Roads & Infrastructure'), ('water', 'Water & Sewerage'), ('electricity', 'Electricity & Street Lights'), ('sanitation', 'Sanitation & Waste'), ('parks', 'Parks & Recreation'), ('health', 'Public Health'), ('building', 'Building & Construction'), ('transport', 'Transport & Traffic'), ('environment', 'Environment & Drainage'), ('fire', 'Fire & Emergency'), ('it', 'IT & Technology'), ('admin_dept', 'General Administration')], max_length=30)),
                ('city_corp', models.CharField(choices=[('DNCC', 'Dhaka North City Corporation'), ('DSCC', 'Dhaka South City Corporation'), ('CCC', 'Chattogram City Corporation'), ('SCC', 'Sylhet City Corporation'), ('RCC', 'Rajshahi City Corporation'), ('KCC', 'Khulna City Corporation'), ('BCC', 'Barishal City Corporation'), ('NCC', 'Narayanganj City Corporation'), ('GCC', 'Gazipur City Corporation'), ('MCC', 'Mymensingh City Corporation')], default='DSCC', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['city_corp', 'name'],
            },
        ),
    ]
