# Generated by Django 5.2.12 on 2026-05-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='city_corp',
            field=models.CharField(choices=[('DNCC', 'Dhaka North City Corporation'), ('DSCC', 'Dhaka South City Corporation'), ('CCC', 'Chattogram City Corporation'), ('SCC', 'Sylhet City Corporation'), ('RCC', 'Rajshahi City Corporation'), ('KCC', 'Khulna City Corporation'), ('BCC', 'Barishal City Corporation'), ('NCC', 'Narayanganj City Corporation'), ('GCC', 'Gazipur City Corporation'), ('MCC', 'Mymensingh City Corporation'), ('COCC', 'Cumilla City Corporation'), ('RNCC', 'Rangpur City Corporation')], default='DSCC', max_length=10),
        ),
    ]
