# Generated by Django 5.2.12 on 2026-05-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('complaint_submitted', 'Complaint Submitted'), ('complaint_assigned', 'Complaint Assigned'), ('survey_request', 'Survey Requested'), ('survey_done', 'Survey Completed'), ('budget_approved', 'Budget Approved'), ('budget_rejected', 'Budget Rejected'), ('worker_assigned', 'Worker Assigned'), ('complaint_resolved', 'Complaint Resolved'), ('duplicate_found', 'Duplicate Detected'), ('transfer_requested', 'Transfer Requested'), ('transfer_approved', 'Transfer Approved'), ('transfer_rejected', 'Transfer Rejected'), ('complaint_merged', 'Complaint Merged'), ('co_reporter_added', 'Added as Co-Reporter'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
